_config.yml
_includes/table_widget.html
assets/js/custom.js
index.html
kgmetadata/biolink.md
kgmetadata/chr.md
kgmetadata/drugbank.md
kgmetadata/ecosim.md
kgmetadata/goldterms.md
kgmetadata/hgnc.md
kgmetadata/interpro.md
kgmetadata/kg-idg.md
kgmetadata/kg-microbe.md
kgmetadata/kg-monarch.md
kgmetadata/kgcl.md
kgmetadata/mixs.md
kgmetadata/neo.md
kgmetadata/orcid.md
kgmetadata/phenio.md
kgmetadata/reacto.md
kgmetadata/reactome.md
kgmetadata/rhea.md
kgmetadata/sgd.md
kgmetadata/swisslipid.md
kgmetadata/uniprot.md
util/schema/registry_schema.json

- Most of this is UI changes based off the current main site with no testing (because of arm64)

UI enhance

---

_includes/head.html
_includes/table_widget.html
assets/js/custom.js

Small enhancements for size of select boxes
Padding the results column away from the filters
flexing the search 100% 
adding light background and padding for domain columns
having filters not expand when search result column changes size

UI enhancements

---

resource/ubergraph.md

Added ubergraph entry with what I think is the correct info

---

resource/ubergraph.md

Fix errors @balhoff pointed out

Fix ubergraph stuff

---

_config.yml
index.html
registry/kgs.jsonld
registry/kgs.nt
registry/kgs.ttl
registry/kgs.yml
registry/obo_context.jsonld
registry/obo_prefixes.ttl
resource/ubergraph.md
util/schema/registry_schema.json

Also fix some formatting issues in resource metadata; make preferredPrefix slot non-required

Add a link to the new resource suggestion template on the homepage

---

_config.yml
registry/kgs.jsonld
registry/kgs.nt
registry/kgs.ttl
registry/kgs.yml
registry/obo_context.jsonld
registry/obo_prefixes.ttl
resource/primekg.md

Add primekg

---

_layouts/resource_detail.html

* Product tables now have column names.
* Product tables now include Biolink compatibility (fix #91).
* Product tables show KGX and Biolink compatibility with symbols.
* All tables have bolder titles.
* Misc other layout cleanup and removal of unused fields

Update display of tables for Resource metadata

---

_layouts/resource_detail.html
assets/css/style.css

Address #127
This will make it "response" with a scroll at lower screens.
The additional change to css is to align those header cards with the rest.
The large block change is an indent.

127 fix overflow

---

.github/workflows/build.yml

copilot generated me this solution. Maybe give it a whirl

99-address-workflow-error

---

_includes/header.html
_layouts/product_detail.html
_layouts/resource_detail.html

Adds link to Resource and Product pages to open an update issue on the GH repo.
Also fixes the main menu link to GH. (Fix #181)

General layout fixes

---

_includes/header.html
_layouts/intro_doc.html
docs/intro/enumerations.md
docs/intro/index.md
docs/intro/products.md
docs/intro/resources.md

Expand docs to include intro and overview

---

Makefile

Move schema-docs target out of make all

---

_config.yml
registry/kgs.jsonld
registry/kgs.yml
reports/metadata-grid.csv
resource/genomickb/genomickb.graph.md
resource/genomickb/genomickb.md
resource/genomickb/genomickb.site.md
src/kg_registry/kg_registry_schema/datamodel/kg_registry_schema.py
src/kg_registry/kg_registry_schema/kg_registry_schema.json
src/kg_registry/kg_registry_schema/schema/kg_registry_schema.yaml

Also add `neo4j` to the `DumpFormatEnum`

Add GenomicKB

---

_config.yml
registry/kgs.jsonld
registry/kgs.yml
reports/metadata-grid.csv
resource/cgnc/cgnc.genes.md
resource/cgnc/cgnc.md
resource/chebi/chebi.md
resource/chebi/chebi.structures.complete.md
resource/chebi/chebi.structures.lite.md
resource/obo-db-ingest/obo-db-ingest.cgnc.json.md
resource/obo-db-ingest/obo-db-ingest.cgnc.obo.md
resource/obo-db-ingest/obo-db-ingest.cgnc.owl.md
resource/obo-db-ingest/obo-db-ingest.cgnc.sssom.tsv.md
resource/obo-db-ingest/obo-db-ingest.md
resource/zfin/zfin.gene-to-phenotype.md
resource/zfin/zfin.gene-to-publication.md
resource/zfin/zfin.md
src/kg_registry/kg_registry_schema/datamodel/kg_registry_schema.py
src/kg_registry/kg_registry_schema/kg_registry_schema.json
src/kg_registry/kg_registry_schema/schema/kg_registry_schema.yaml

Also added new formats to FormatEnum.

General metadata updates: CHEBI, ZFIN, CGNC

---

_config.yml
registry/kgs.jsonld
registry/kgs.yml
reports/metadata-grid.csv
resource/gutmgene/gutmgene.md
resource/gutmgene/gutmgene.site.md
resource/mgmlink/mgmlink.code.md
resource/mgmlink/mgmlink.md
resource/pheknowlator/pheknowlator.code.md
resource/pheknowlator/pheknowlator.md

Also update Pheknowlator entry

Add MGMLink and GutMGene

---

_layouts/product_detail.html
_layouts/resource_detail.html
assets/js/custom.js

Icons everywhere! Not the final choices, particularly for the Knowledge Graph icon. That may need a bespoke selection.

Frontend and script improvements, including icons

---

_config.yml
_data/schema.yaml
_includes/table_widget.html
_layouts/resource_detail.html
assets/js/custom.js
registry/kgs.jsonld
registry/kgs.yml
resource/automat/automat.md
resource/clinical-data-kp/clinical-data-kp.md
resource/connections-hypothesis-kp/connections-hypothesis-kp.md
resource/genetics-kp/genetics-kp.md
resource/molecular-data-kp/molecular-data-kp.md
resource/multiomics-kp/multiomics-kp.md
resource/ontology-kp/ontology-kp.md
resource/rtx-kg2/rtx-kg2.md
resource/service-kp/service-kp.md
resource/text-mining-kp/text-mining-kp.md
src/kg_registry/kg_registry_schema/datamodel/kg_registry_schema.py
src/kg_registry/kg_registry_schema/kg_registry_schema.json
src/kg_registry/kg_registry_schema/schema/kg_registry_schema.yaml

The main page now allows filtering by collection.
Collections are also noted on Resource pages where applicable.

Add collections, frontend updates for collections, and Translator collection membership

---

_config.yml
registry/kgs.jsonld
registry/kgs.yml
reports/metadata-grid.csv
resource/chebi/chebi.md
resource/do/do.code.utils.md
resource/do/do.md
resource/do/do.obo.md
resource/do/do.owl.md
resource/drug-approvals-kp/drug-approvals-kp.code.md
resource/drug-approvals-kp/drug-approvals-kp.graph.edges.md
resource/drug-approvals-kp/drug-approvals-kp.graph.nodes.md
resource/drug-approvals-kp/drug-approvals-kp.md
resource/hgnc/hgnc.md
resource/hp/hp.code.md
resource/hp/hp.md
resource/hp/hp.obo.md
resource/hp/hp.owl.md
resource/mondo/mondo.json.md
resource/mondo/mondo.md
resource/mondo/mondo.obo.md
resource/mondo/mondo.owl.md
resource/mondo/mondo.sssom.md

Added DO, HP, and MONDO as original sources.

Add Drug Approvals KP and three source ontologies

---

_config.yml
poetry.lock
registry/kgs.jsonld
registry/kgs.yml
reports/metadata-grid.csv
resource/kg-jensenlab-diseases/kg-jensenlab-diseases.md
resource/kg-jensenlab-diseases/kg-jensenlab-diseases_kgx-edges.md
resource/kg-jensenlab-diseases/kg-jensenlab-diseases_kgx-nodes.md
resource/kg-jensenlab-diseases/kg-jensenlab-diseases_trapi-edges.md
util/count_format.py

The utility `count_format.py` provides a quick count of resources, products, and formats in the Registry.

Refresh registry artifacts and add new utility

---

resource/kg-ebi-gene2pheno/kg-ebi-gene2pheno.md

Part of the same Translator ingest effort as #253. 
I wrote this entry based on the DISEASES entry.

add draft Translator EBI gene2pheno ingest

---

_includes/table_widget.html
assets/js/custom.js

Add Resource count badge to main page

---

_config.yml
registry/kgs.jsonld
registry/kgs.yml
resource/drugbank/drugbank.academic.md
resource/drugbank/drugbank.clinical.api.md
resource/drugbank/drugbank.md
resource/drugbank/drugbank.web.md
resource/eco-kg/eco-kg.api.md
resource/eco-kg/eco-kg.graph.md
resource/eco-kg/eco-kg.md
resource/ecocyc/ecocyc.api.md
resource/ecocyc/ecocyc.md
resource/ecocyc/ecocyc.metabolic_model.md
resource/ecocyc/ecocyc.web.md
resource/goldterms/goldterms.bioportal.md
resource/goldterms/goldterms.data.owl.md
resource/goldterms/goldterms.definitions.yaml.md
resource/goldterms/goldterms.md

* DrugBank
* Eco-KG
* EcoCyc
* GOLD

Update metadata for 4 entries

---

_config.yml
_data/schema.yaml
registry/kgs.jsonld
registry/kgs.yml
resource/cellosaurus/cellosaurus.clastr.md
resource/cellosaurus/cellosaurus.md
resource/cellosaurus/cellosaurus.site.md
resource/cpathkg/cpathkg.code.md
resource/cpathkg/cpathkg.md
resource/interpro/interpro.interproscan.md
resource/interpro/interpro.md
resource/pfam/pfam.md
resource/pfam/pfam.site.md
resource/skos/skos.core.md
resource/skos/skos.md
resource/skos/skos.reference.md
resource/spoke/spoke.md
resource/spoke/spoke.neighborhood_explorer.md
src/kg_registry/kg_registry_schema/datamodel/kg_registry_schema.py
src/kg_registry/kg_registry_schema/kg_registry_schema.json
src/kg_registry/kg_registry_schema/schema/kg_registry_schema.yaml

Added python, java, javascript, and "mixed" to handle cases of mixed format/standard.

Add more formats to the FormatEnum

---

_config.yml
_data/schema.yaml
registry/kgs.jsonld
registry/kgs.yml
resource/bfo/bfo.md
resource/bfo/bfo.obo.md
resource/bfo/bfo.owl.md
resource/bto/bto.json.md
resource/bto/bto.md
resource/bto/bto.obo.md
resource/bto/bto.owl.md
resource/chemicalchecker/chemicalchecker.api.md
resource/chemicalchecker/chemicalchecker.md
resource/chemicalchecker/chemicalchecker.signatures.md
resource/chemicalchecker/chemicalchecker.signaturizer.md
src/kg_registry/kg_registry_schema/datamodel/kg_registry_schema.py
src/kg_registry/kg_registry_schema/kg_registry_schema.json
src/kg_registry/kg_registry_schema/schema/kg_registry_schema.yaml

Update pages for bfo, bto, and chemicalchecker

---

_config.yml
registry/kgs.jsonld
registry/kgs.yml
resource/ensembl/ensembl.md
resource/go/go.md
resource/medgen/medgen.md
resource/ncbigene/ncbigene.gene2accession.md
resource/ncbigene/ncbigene.gene2ensembl.md
resource/ncbigene/ncbigene.gene2go.md
resource/ncbigene/ncbigene.gene2pubmed.md
resource/ncbigene/ncbigene.gene2refseq.md
resource/ncbigene/ncbigene.gene_group.md
resource/ncbigene/ncbigene.gene_history.md
resource/ncbigene/ncbigene.gene_info.md
resource/ncbigene/ncbigene.gene_neighbors.md
resource/ncbigene/ncbigene.gene_orthologs.md
resource/ncbigene/ncbigene.gene_refseq_uniprotkb_collab.md
resource/ncbigene/ncbigene.gene_summary.md
resource/ncbigene/ncbigene.md
resource/ncbigene/ncbigene.mim2gene_medgen.md
resource/ncbigene/ncbigene.search.md
resource/omim/omim.md
resource/pubmed/pubmed.md
resource/refseq/refseq.md
resource/uniprot/uniprot.md
tools/robot

This PR adds complete information for the NCBI Gene resource to replace the existing stub page.
- Updated NCBI Gene resource (resource/ncbigene/ncbigene.md):
- Replaced stub page with comprehensive resource information
- Added proper description from issue request
- Added all downloadable products from https://ftp.ncbi.nih.gov/gene/DATA/
- Added Gene search interface as specifically requested
- Included contact information, licensing, and metadata
- Added reference publication and repository links
- Removed stub domain and warnings
The resource now includes 13 downloadable data products:
- Gene to accession mapping
- Gene to Ensembl mapping  
- Gene to GO mapping
- Gene to PubMed mapping
- Gene to RefSeq mapping
- Gene group data
- Gene history data
- Gene information (main dataset)
- …

Add comprehensive NCBI Gene resource information

---

resource/insight/insight.md
src/kg_registry/kg_registry_schema/datamodel/kg_registry_schema.py
src/kg_registry/kg_registry_schema/kg_registry_schema.json
src/kg_registry/kg_registry_schema/schema/kg_registry_schema.yaml
src/kg_registry/kg_registry_schema/schema/kg_registry_schema_all.yaml

Also add `aop` to CollectionEnum and `toxicology` to DomainEnum.

Add insight page
